# Generated by Django 5.2.15 on 2026-06-06 16:38

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_or_husband_name', models.CharField(max_length=150)),
                ('cnic', apps.core.fields.EncryptedCharField(validators=[django.core.validators.RegexValidator(message='Enter a valid CNIC in the format 42101-1234567-1.', regex='^\\d{5}-\\d{7}-\\d$')])),
                ('cnic_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number, e.g. 0301-2345678.', regex='^(?:\\+92|0092|0)?3\\d{2}[-\\s]?\\d{7}$|^(?:\\+92|0092|0)?\\d{2,4}[-\\s]?\\d{6,8}$')])),
                ('alt_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number, e.g. 0301-2345678.', regex='^(?:\\+92|0092|0)?3\\d{2}[-\\s]?\\d{7}$|^(?:\\+92|0092|0)?\\d{2,4}[-\\s]?\\d{6,8}$')])),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('household_size', models.PositiveSmallIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_pii', 'Can view unmasked CNIC and identity documents'), ('review_application', 'Can review membership applications (first stage)'), ('approve_membership', 'Can grant final membership approval')],
            },
        ),
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_number', models.CharField(max_length=20)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='members.memberprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_class', models.CharField(choices=[('permanent', 'Permanent Member (مستقل ممبر)'), ('associate', 'Associate Member (ایسوسی ایٹ ممبر)')], max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_approvals', to=settings.AUTH_USER_MODEL)),
                ('approved_by_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_approvals', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.memberprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_or_husband_name', models.CharField(max_length=150)),
                ('cnic', apps.core.fields.EncryptedCharField(validators=[django.core.validators.RegexValidator(message='Enter a valid CNIC in the format 42101-1234567-1.', regex='^\\d{5}-\\d{7}-\\d$')])),
                ('cnic_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number, e.g. 0301-2345678.', regex='^(?:\\+92|0092|0)?3\\d{2}[-\\s]?\\d{7}$|^(?:\\+92|0092|0)?\\d{2,4}[-\\s]?\\d{6,8}$')])),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('household_size', models.PositiveSmallIntegerField(default=1)),
                ('residency_type', models.CharField(choices=[('owner', 'Owner (مالک)'), ('tenant', 'Tenant (کرایہ دار)')], max_length=8)),
                ('requested_class', models.CharField(choices=[('permanent', 'Permanent Member (مستقل ممبر)'), ('associate', 'Associate Member (ایسوسی ایٹ ممبر)')], max_length=10)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('declaration_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('docs_required', 'Documents required'), ('under_review', 'Under review'), ('secretary_approved', 'Secretary approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('member_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_applications', to='members.memberprofile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='locality.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Staff member, if this was an assisted (walk-in) registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], default='cash', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('receipt_number', models.CharField(max_length=24, unique=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_fees', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='members.memberprofile')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='members.membershipapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('cnic_front', 'CNIC (front)'), ('cnic_back', 'CNIC (back)'), ('tenancy_agreement', 'Tenancy agreement'), ('photo', 'Photograph'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='application_docs/%Y/%m/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.membershipapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residency_type', models.CharField(choices=[('owner', 'Owner (مالک)'), ('tenant', 'Tenant (کرایہ دار)')], max_length=8)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to='members.memberprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residencies', to='locality.property')),
            ],
            options={
                'verbose_name_plural': 'residencies',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['member_number'], name='members_mem_member__a8432e_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['status'], name='members_mem_status_e09a87_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['status'], name='members_mem_status_d09784_idx'),
        ),
    ]
