# Generated by Django 5.2.15 on 2026-06-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-published_at'], 'permissions': [('broadcast_notice', 'Can broadcast notices to members')]},
        ),
    ]
