# Generated by Django 5.2.15 on 2026-06-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_organizationprofile_organizationgoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('land', 'Land & plots'), ('building', 'Buildings'), ('vehicle', 'Vehicles'), ('equipment', 'Equipment'), ('furniture', 'Furniture & fixtures'), ('fund', 'Funds & reserves'), ('other', 'Other')], default='other', max_length=12)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('is_public', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'permissions': [('manage_assets', 'Can add and manage organization assets')],
            },
        ),
    ]
