# Generated by Django 5.2.15 on 2026-06-06 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('applies_to', models.CharField(choices=[('all', 'All properties'), ('owner', 'Owner-occupied'), ('tenant', 'Tenant-occupied')], default='all', max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('record_payment', 'Can record dues/donation payments'), ('approve_expense', 'Can approve expenses')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], default='cash', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('receipt_number', models.CharField(max_length=24, unique=True)),
                ('donated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False, help_text='Show on the public donor wall (consent).')),
                ('donor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.memberprofile')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='DuesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='members.memberprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='locality.property')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='dues.duesplan')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='DuesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], default='cash', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('receipt_number', models.CharField(max_length=24, unique=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dues.duesinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('incurred_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expense_docs/%Y/%m/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_on'],
            },
        ),
        migrations.AddIndex(
            model_name='duesinvoice',
            index=models.Index(fields=['property', 'period_start'], name='dues_duesin_propert_891bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='duesinvoice',
            index=models.Index(fields=['status'], name='dues_duesin_status_603b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='duesinvoice',
            index=models.Index(fields=['due_date'], name='dues_duesin_due_dat_742cfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='duesinvoice',
            constraint=models.UniqueConstraint(fields=('property', 'plan', 'period_start'), name='uniq_invoice_period'),
        ),
    ]
