# Generated by Django 5.2.15 on 2026-06-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pays_registration', models.BooleanField(default=False)),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dues_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('donation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], default='bank_transfer', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('proof', models.FileField(upload_to='payment_proofs/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('invoices', models.ManyToManyField(blank=True, related_name='submissions', to='dues.duesinvoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to='members.memberprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='dues_paymen_status_cbbdeb_idx')],
            },
        ),
    ]
