# Generated by Django 5.2.15 on 2026-06-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=16)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sectors', to='locality.sector')),
            ],
            options={
                'ordering': ['sector__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_number', models.CharField(max_length=32)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('plot', 'Plot'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], default='house', max_length=16)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('under_construction', 'Under construction')], default='occupied', max_length=20)),
                ('sub_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locality.subsector')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['sub_sector', 'house_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='subsector',
            constraint=models.UniqueConstraint(fields=('sector', 'code'), name='uniq_subsector_code'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['house_number'], name='locality_pr_house_n_cd1ef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('sub_sector', 'house_number'), name='uniq_property_house'),
        ),
    ]
